# Generated by Django 6.0.6 on 2026-08-15 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0007_substituicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('nome_curto', models.CharField(blank=True, max_length=60)),
                ('tooltip', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('estrutural', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='competencias.acao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='user_admin.unidade')),
            ],
            options={
                'verbose_name': 'Atribuição de unidade',
                'verbose_name_plural': 'Atribuições de unidade',
            },
        ),
        migrations.CreateModel(
            name='Concessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedida_em', models.DateTimeField(auto_now_add=True)),
                ('atribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessoes', to='competencias.atribuicaounidade')),
                ('cargo_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concessoes', to='user_admin.cargobase')),
                ('cargo_comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concessoes', to='user_admin.cargocomissao')),
                ('concedida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concessão',
                'verbose_name_plural': 'Concessões',
            },
        ),
        migrations.AddConstraint(
            model_name='atribuicaounidade',
            constraint=models.UniqueConstraint(fields=('unidade', 'acao'), name='atribuicao_unica_por_unidade_e_acao'),
        ),
        migrations.AddConstraint(
            model_name='concessao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cargo_base__isnull', False), ('cargo_comissao__isnull', True)), models.Q(('cargo_base__isnull', True), ('cargo_comissao__isnull', False)), _connector='OR'), name='concessao_exatamente_um_cargo'),
        ),
        migrations.AddConstraint(
            model_name='concessao',
            constraint=models.UniqueConstraint(condition=models.Q(('cargo_base__isnull', False)), fields=('atribuicao', 'cargo_base'), name='concessao_unica_por_cargo_base'),
        ),
        migrations.AddConstraint(
            model_name='concessao',
            constraint=models.UniqueConstraint(condition=models.Q(('cargo_comissao__isnull', False)), fields=('atribuicao', 'cargo_comissao'), name='concessao_unica_por_cargo_comissao'),
        ),
    ]
