# Generated by Django 6.0.6 on 2026-08-17 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0001_initial'),
        ('user_admin', '0007_substituicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.BooleanField()),
                ('operacao', models.CharField(blank=True, max_length=40)),
                ('alvo_tipo', models.CharField(blank=True, max_length=40)),
                ('alvo_identificador', models.CharField(blank=True, max_length=120)),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_executadas', to='competencias.acao')),
                ('cargo_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_executadas', to='user_admin.cargobase')),
                ('cargo_comissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes_executadas', to='user_admin.cargocomissao')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_executadas', to=settings.AUTH_USER_MODEL)),
                ('substituindo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_cobertas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_executadas', to='user_admin.unidade')),
            ],
            options={
                'verbose_name': 'Execução de ação',
                'verbose_name_plural': 'Execuções de ação',
            },
        ),
    ]
