# Generated by Django 6.0.6 on 2026-08-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0003_unidade_muda_de_app'),
        ('unidades', '0002_renomear_tabelas_e_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacoes', to='competencias.acao')),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('delegante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacoes', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Delegação de competência',
                'verbose_name_plural': 'Delegações de competência',
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='delegacao_fim_nao_antecede_inicio')],
            },
        ),
    ]
