# Generated by Django 6.0.6 on 2026-08-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_delegacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicaounidade',
            name='extinta_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concessao',
            name='extinta_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
