# Generated by Django 6.0.6 on 2026-08-31 12:58

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_renomear_tabelas_e_content_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'base_manager_name': 'todas', 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelManagers(
            name='unidade',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='unidade',
            name='extinta_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.CheckConstraint(condition=models.Q(('pai__isnull', False), ('extinta_em__isnull', True), _connector='OR'), name='unidade_raiz_nao_se_extingue'),
        ),
    ]
