# Generated by Django 6.0.6 on 2026-10-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_alter_unidade_options_alter_unidade_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidade',
            name='extinto_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
