# Generated by Django 6.0.6 on 2026-10-09 19:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodificacaoGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.TextField()),
                ('consulta', models.TextField()),
                ('provedor', models.CharField(max_length=20)),
                ('consultado_em', models.DateTimeField()),
                ('ponto', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('endereco_formatado', models.TextField()),
                ('logradouro', models.TextField(null=True)),
                ('numero', models.TextField(null=True)),
                ('bairro', models.TextField(null=True)),
                ('municipio', models.TextField(null=True)),
                ('uf', models.TextField(null=True)),
                ('cep', models.TextField(null=True)),
                ('precisao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Geocodificação guardada',
                'verbose_name_plural': 'Geocodificações guardadas',
                'constraints': [models.UniqueConstraint(fields=('chave',), name='geocodificacao_guardada_unica')],
            },
        ),
    ]
