# Generated by Django 6.0.6 on 2026-09-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0006_cargos_muda_de_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('arquivo', models.BinaryField()),
                ('envelope', models.JSONField(editable=False)),
                ('campos_publicos', models.JSONField(default=list, editable=False)),
                ('emitido_em', models.DateTimeField(editable=False)),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='competencias.execucaoacao')),
            ],
            options={
                'verbose_name': 'Documento emitido',
                'verbose_name_plural': 'Documentos emitidos',
                'indexes': [models.Index(fields=['-emitido_em'], name='documentos__emitido_3cc903_idx')],
            },
        ),
    ]
