# Generated by Django 6.0.6 on 2026-08-05 15:29

import apps.user_admin.models.user
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo base',
                'verbose_name_plural': 'Cargos base',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='CargoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('e_chefia', models.BooleanField()),
                ('alta_administracao', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo em comissão',
                'verbose_name_plural': 'Cargos em comissão',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alta_administracao', True), ('nivel__isnull', True)), models.Q(('alta_administracao', False), ('nivel__gte', 1), ('nivel__lte', 6)), _connector='OR'), name='cargo_comissao_nivel_conforme_alta_administracao'), models.CheckConstraint(condition=models.Q(('alta_administracao', False), ('e_chefia', True), _connector='OR'), name='cargo_comissao_alta_administracao_e_chefia')],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rf', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='user_admin.cargobase')),
                ('cargo_comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='user_admin.cargocomissao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='user_admin.unidade')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
            managers=[
                ('objects', apps.user_admin.models.user.PerfilManager()),
            ],
        ),
    ]
