# Generated by Django 6.0.6 on 2026-08-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('sigla', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de impedimento',
                'verbose_name_plural': 'Tipos de impedimento',
                'constraints': [models.UniqueConstraint(condition=models.Q(('sigla', ''), _negated=True), fields=('sigla',), name='tipo_impedimento_sigla_unica')],
            },
        ),
        migrations.CreateModel(
            name='Impedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impedimentos', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impedimentos', to='user_admin.tipoimpedimento')),
            ],
            options={
                'verbose_name': 'Impedimento',
                'verbose_name_plural': 'Impedimentos',
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='impedimento_fim_nao_antecede_inicio')],
            },
        ),
    ]
