# Generated by Django 6.0.6 on 2026-08-05 18:20

import django.db.models.deletion
from django.db import migrations, models


def criar_tipo_minimo_e_associar_unidades_existentes(apps, schema_editor):
    # A SPEC presume a tabela vazia; onde já há unidade cadastrada (ex.: a raiz DIMAP), o dado é
    # preservado com um tipo-raiz mínimo em vez de perdido — o seed do épico substitui isso depois.
    TipoUnidade = apps.get_model("user_admin", "TipoUnidade")
    Unidade = apps.get_model("user_admin", "Unidade")
    unidades_sem_tipo = Unidade.objects.filter(tipo__isnull=True)
    if not unidades_sem_tipo.exists():
        return
    tipo_raiz, _ = TipoUnidade.objects.get_or_create(
        nome="Secretaria",
        defaults={"nivel": 100, "pode_ser_raiz": True},
    )
    unidades_sem_tipo.update(tipo=tipo_raiz)


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_tipoimpedimento_impedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='user_admin.unidade'),
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('pode_ser_raiz', models.BooleanField(default=False)),
                ('tipos_filhos_vedados', models.ManyToManyField(blank=True, related_name='vedado_como_filho_em', to='user_admin.tipounidade')),
            ],
            options={
                'verbose_name': 'Tipo de unidade',
                'verbose_name_plural': 'Tipos de unidade',
            },
        ),
        migrations.AddField(
            model_name='unidade',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='user_admin.tipounidade'),
        ),
        migrations.RunPython(
            criar_tipo_minimo_e_associar_unidades_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='unidade',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='user_admin.tipounidade'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.CheckConstraint(condition=models.Q(('pai', models.F('id')), _negated=True), name='unidade_nao_e_pai_de_si_mesma'),
        ),
    ]
