# Generated by Django 6.0.6 on 2026-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_unidade_pai_tipounidade_unidade_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cor',
            field=models.CharField(choices=[('agua-700', 'Água 700'), ('agua-800', 'Água 800'), ('rocha-700', 'Rocha 700'), ('rocha-900', 'Rocha 900'), ('madeira-600', 'Madeira 600'), ('madeira-700', 'Madeira 700'), ('sakura-600', 'Sakura 600'), ('sakura-700', 'Sakura 700')], default='agua-700', max_length=20),
        ),
    ]
