# Generated by Django 6.0.6 on 2026-08-12 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_admin', '0005_perfil_foto_nome_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='e_titular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='exige_alta_administracao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='nivel_minimo_titular',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('e_titular', True)), fields=('unidade',), name='unidade_tem_um_titular'),
        ),
        migrations.AddConstraint(
            model_name='tipounidade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exige_alta_administracao', True), ('nivel_minimo_titular__isnull', True)), models.Q(('exige_alta_administracao', False), ('nivel_minimo_titular__gte', 1), ('nivel_minimo_titular__lte', 6)), _connector='OR'), name='tipo_unidade_minimo_conforme_alta_administracao'),
        ),
    ]
