# Generated by Django 6.0.6 on 2026-08-13 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_perfil_e_titular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('impedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='user_admin.impedimento')),
                ('substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substituicoes_exercidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substituição',
                'verbose_name_plural': 'Substituições',
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='substituicao_fim_nao_antecede_inicio')],
            },
        ),
    ]
