# Generated by Django 6.0.6 on 2026-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_admin', '0007_substituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='senha_provisoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='email_unico_quando_preenchido'),
        ),
    ]
