# Generated by Django 6.0.6 on 2026-08-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_admin', '0008_perfil_email_perfil_senha_provisoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rf',
            field=models.CharField(error_messages={'unique': 'Já existe servidor cadastrado com este RF.'}, max_length=20, unique=True),
        ),
        migrations.AlterConstraint(
            model_name='perfil',
            name='email_unico_quando_preenchido',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='email_unico_quando_preenchido', violation_error_code='unique', violation_error_message='Já existe servidor cadastrado com este e-mail.'),
        ),
    ]
