# Generated by Django 6.0.6 on 2026-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0010_unidade_muda_de_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='exonerado_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
