# Generated by Django 6.0.6 on 2026-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0012_backfill_exonerado_em'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exonerado_em__isnull', True), ('is_active', True)), models.Q(('exonerado_em__isnull', False), ('is_active', False)), _connector='OR'), name='perfil_exonerado_tem_data'),
        ),
    ]
