# Generated by Django 6.0.6 on 2026-09-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocomissao',
            name='extinto_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
