# Generated by Django 6.0.6 on 2026-09-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargocomissao_extinto_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargobase',
            name='extinto_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
